services:
  proxy:
    image: nginx
    container_name: proxy
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node-network

  app:
    build:
      context: node
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    # ports:
    #   - 3000:3000
    tty: true
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s npm start
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
